name: WarpPortalCommands
main: me.wpc.main
version: 1.2
commands:
  set-warp-portal-command:
    description: Sets and adds commands to run when walking through warp portals.
    aliases: [swpc,awpc]
  del-warp-portal-command:
    description: Delete commands from warp portals.
    aliases: dwpc
  list-warp-portal-command:
    description: Delete commands from warp portals.
    aliases: [lwpc,view-warp-portal-command,vwpc]
  wpc:
    description: Basic command for WarpPortalCommands.